### ISSUE TITLE
Purge static files

### ISSUE THREAD

**Issue by travisbotello** [GoldCoastMedia/modx-varnish-purge#2]
Hello,

is it possible to purge the entire varnish website cache including static files like images, css and js files when the MODx cache is cleared?

I enabled the varnishpurge.purge_website setting and added my assets domains to the varnishpurge.domains but this doesn't do anything. It only purges the exact domain entered. 

This means purging http://example.com/ only purges the home page and NOT the entire website cache which leads to various problems when using the file manager and adding, removing or overwriting files.

Any ideas? I am running varnish 4.0.1 and MODx Revo 2.4.2.

**Comment by Gibbs** [comment]
If you replace http://example.com/ with just example.com it should work from the top of my head.

**Comment by travisbotello** [comment]
This leads to the following error log

```
PHP notice: Undefined index: host
Language string not found: "varnishpurge.rescode_0"
Varnish Purge: Failed purge on /example.com. 0 (varnishpurge.rescode_0)
```

Also the purging is not reaching or triggering my varnish backend as I am monitoring the live logs via varnishlog.

**Comment by travisbotello** [comment]
My understanding from the official varnish documentation is that since Version 3 the PURGE method only removes the copy of one specified URL. In my prior example this is the home page.

To purge the entire website/domain we need to implement something like BAN using regular expressions. However it might be more efficient to hook into modx file manager events and pass the file name to $vp->purge(). Therefore all other resources can stay in the cache.

**Comment by travisbotello** [comment]
This commit is solving my problems...

https://github.com/travisbotello/modx-varnish-purge/commit/abb91effcbbcfd0386641fc2604dd278e0dc3567

**Comment by Gibbs** [comment]
Excellent. Feel free to send a PR and I'll get this marked as closed.

**Comment by travisbotello** [comment]
done.

https://github.com/GoldCoastMedia/modx-varnish-purge/pull/3

**Comment by Gibbs** [comment]
Thanks, appreciated
